# Generated by Django 3.2.3 on 2021-06-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'bay',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_money', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('total_money', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('opening_date', models.DateTimeField(max_length=100)),
                ('closing_date', models.DateTimeField(max_length=100, null=True)),
                ('state', models.BooleanField()),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='imagesParking')),
            ],
            options={
                'db_table': 'parkinglot',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('doc_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'tariff',
            },
        ),
        migrations.CreateModel(
            name='TypeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.tariff')),
            ],
            options={
                'db_table': 'typevehicle',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('vehicle_photo', models.ImageField(upload_to='imagesCar')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.person')),
                ('typevehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.typevehicle')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(max_length=100)),
                ('total_time', models.FloatField(null=True)),
                ('departure_time', models.DateTimeField(max_length=100, null=True)),
                ('cost', models.FloatField(null=True)),
                ('date', models.DateField(max_length=100)),
                ('bay_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parqueadero.bay')),
                ('cash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.cash')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.vehicle')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='bay',
            name='par_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parkinglot'),
        ),
    ]
